export const API_BASE_URL = 'http://192.168.1.110:8000/api/v1/cart-order';
export const AUTH_BASE_URL = 'http://192.168.1.110:8000/api/v1';

export const ORDER_STATUS = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  READY_FOR_DELIVERY: 'READY_FOR_DELIVERY',
  ASSIGNED_TO_DELIVERER: 'ASSIGNED_TO_DELIVERER',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  DELIVERY_CONFIRMED: 'DELIVERY_CONFIRMED',
  FAILED: 'FAILED',
  CANCELED: 'CANCELED',
};

export const STATUS_COLORS = {
  PENDING: 'bg-yellow-500',
  PROCESSING: 'bg-blue-500',
  READY_FOR_DELIVERY: 'bg-purple-500',
  ASSIGNED_TO_DELIVERER: 'bg-indigo-500',
  OUT_FOR_DELIVERY: 'bg-teal-500',
  DELIVERED: 'bg-green-500',
  DELIVERY_CONFIRMED: 'bg-emerald-600',
  FAILED: 'bg-red-600',
  CANCELED: 'bg-gray-600',
};

export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
};